Protect Seed input restore page from screenshots
planetdecred/dcrandroid pull request #614
Opened 2022-02-17 21:30 UTC by macsleven

closes #612

2022-02-25 09:25 UTC, JustinBeBoy requested changes

2022-02-25 09:25 UTC, JustinBeBoy commented on app/src/main/java/com/dcrandroid/activities/RestoreWalletActivity.kt
> +
Remove line

2022-02-25 09:25 UTC, JustinBeBoy commented on app/src/main/java/com/dcrandroid/activities/privacy/AccountMixerActivity.kt
> +        multiWallet!!.addTxAndBlockNotificationListener(this, true,this.javaClass.name)
please format it

2022-03-04 18:37 UTC, dreacot requested changes

2022-03-04 18:37 UTC, dreacot commented on build.gradle
> +    ext.kotlin_version = '1.6.10'
this shouldn't be updated, at least not in this pr

2022-03-04 18:37 UTC, dreacot commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.1.1'
this shouldn't be updated, at least not in this pr

2022-03-04 18:37 UTC, dreacot commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
this shouldn't be updated, at least not in this pr

2022-03-04 18:37 UTC, dreacot commented on dcrlibwallet-ci-build.sh
> +go get golang.org/x/mobile/bind
the build script doesn't need to be updated

2022-04-26 18:36 UTC, yaroyazeed submitted a review, later dismissed

2022-04-28 22:34 UTC, yaroyazeed approved these changes

2022-04-29 01:42 UTC, merged